@host = http://localhost:8080/api/v1/
## GET status
GET {{host}}/status
Content-Type: application/json

###

POST {{host}}/start
Content-Type: application/json
Accept: application/json

{
  "hostname": "new cs server",
  "password": "",
  "start_map": "de_mirage",
  "max_players": 0,
  "steam_login_token": ""
}

###


## POST stop
POST {{host}}/stop

###

## POST send-command
POST {{host}}/send-command

{
  "command": "status"
}

###